name = "DescribedTypes"
uuid = "8741edd9-8b82-4aab-aab4-ad85b116ccea"
version = "1.0.2"
authors = ["Marius Fersigan <marius.fersigan@gmail.com>"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
